/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "tertiary-container": "#006e5a",
        "on-secondary": "#ffffff",
        "secondary-container": "#7bf8a1",
        "tertiary-fixed": "#6ff9d6",
        "error-container": "#ffdad6",
        "on-secondary-fixed": "#00210c",
        "on-tertiary-container": "#68f3d0",
        "outline-variant": "#bec9c3",
        "on-secondary-container": "#007239",
        "secondary-fixed": "#7efba4",
        "on-primary-fixed": "#002117",
        "primary-container": "#0f6e56",
        "surface-tint": "#086b53",
        "on-primary": "#ffffff",
        "on-surface-variant": "#3f4944",
        "surface-container-highest": "#e2e0fc",
        "surface-bright": "#fcf8ff",
        "on-tertiary-fixed-variant": "#005141",
        "surface-container-high": "#e8e5ff",
        "on-primary-fixed-variant": "#00513e",
        "primary-fixed-dim": "#84d6b9",
        "on-error": "#ffffff",
        "on-tertiary-fixed": "#002019",
        "primary-fixed": "#a0f3d4",
        "inverse-on-surface": "#f2efff",
        "on-error-container": "#93000a",
        "error": "#ba1a1a",
        "tertiary-fixed-dim": "#4eddbb",
        "background": "#fcf8ff",
        "surface-dim": "#dad7f3",
        "on-background": "#1a1a2e",
        "surface-variant": "#e2e0fc",
        "outline": "#6f7a74",
        "inverse-surface": "#2f2e43",
        "tertiary": "#005344",
        "on-surface": "#1a1a2e",
        "on-primary-container": "#9aedcf",
        "surface-container-lowest": "#ffffff",
        "secondary-fixed-dim": "#61de8a",
        "secondary": "#006d37",
        "inverse-primary": "#84d6b9",
        "surface-container": "#efecff",
        "on-secondary-fixed-variant": "#005228",
        "surface-container-low": "#f5f2ff",
        "surface": "#fcf8ff",
        "primary": "#005440",
        "on-tertiary": "#ffffff"
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
      spacing: {
        "xl": "32px",
        "md": "16px",
        "margin-mobile": "16px",
        "gutter": "24px",
        "base": "4px",
        "lg": "24px",
        "margin-desktop": "32px",
        "xs": "4px",
        "sm": "8px"
      },
      fontFamily: {
        "headline-sm": ["Inter", "sans-serif"],
        "headline-md": ["Inter", "sans-serif"],
        "body-lg": ["Inter", "sans-serif"],
        "title-md": ["Inter", "sans-serif"],
        "headline-lg-mobile": ["Inter", "sans-serif"],
        "headline-lg": ["Inter", "sans-serif"],
        "label-md": ["Inter", "sans-serif"],
        "headline-xl": ["Inter", "sans-serif"],
        "body-md": ["Inter", "sans-serif"]
      },
      fontSize: {
        "headline-sm": ["18px", { lineHeight: "26px", fontWeight: "600" }],
        "headline-md": ["22px", { lineHeight: "30px", fontWeight: "600" }],
        "body-lg": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "title-md": ["16px", { lineHeight: "24px", fontWeight: "600" }],
        "headline-lg-mobile": ["24px", { lineHeight: "32px", fontWeight: "700" }],
        "headline-lg": ["28px", { lineHeight: "36px", letterSpacing: "-0.01em", fontWeight: "700" }],
        "label-md": ["12px", { lineHeight: "16px", letterSpacing: "0.02em", fontWeight: "500" }],
        "headline-xl": ["32px", { lineHeight: "40px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "body-md": ["14px", { lineHeight: "20px", fontWeight: "400" }]
      }
    },
  },
  plugins: [
    require('@tailwindcss/forms'),
    require('@tailwindcss/container-queries')
  ],
}
